uploads = []

[[generated]]
id = "-DvKwu1YAu_oOGBwEZCDd"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BNbLrY5Cn75rBBt9kk6eT"
uri = "file://SRS_LohParkir_UseCase_Diagram.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "vV4_G9I3fUj43sHW34SvQ"
uri = "file://SRS_LohParkir_UseCase.md"
type = "text"
title = "SRS LohParkir - Use Case Document"

[[outputs]]
id = "4FtVVcqFDcrGC9bofRkaV"
uri = "file://screenshots/usecase-diagram.jpg"
type = "image"
title = "Use Case Diagram - Sistem LohParkir"

[[outputs]]
id = "AFezSEhf79AzaNgllmho6"
uri = "file://screenshots/data-transfer-usecase.jpg"
type = "image"
title = "Data Transfer pada Use Case Diagram - Sistem LohParkir"

[[outputs]]
id = "z5mcCDBNMvT92T67p2ZwQ"
uri = "file://screenshots/usecase-diagram-annotated.jpg"
type = "image"
title = "Use Case Diagram + Data Transfer - Sistem LohParkir"

[[outputs]]
id = "EldEsg2X8uwHtYwso2631"
uri = "file://screenshots/erd-lohparkir.jpg"
type = "image"
title = "ERD (Entity Relationship Diagram) - Sistem LohParkir"

[[outputs]]
id = "1FDKqeAp6KF2s4Q0ktVeP"
uri = "file://screenshots/nfr-lohparkir.jpg"
type = "image"
title = "Non-Functional Requirements (NFR) - Sistem LohParkir"

[[outputs]]
id = "IjtUHnlsiVJj02lluEiT5"
uri = "file://screenshots/kuesioner-lohparkir.jpg"
type = "image"
title = "Kuesioner Analisis Kebutuhan Fitur - Aplikasi LohParkir"
